version: "3.3"

services:
    client:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./src:/usr/share/nginx/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        logging:
            driver: "fluentd"
            options:
              fluentd-address: localhost:24224
              tag: "nginx.access"
        depends_on:
            - "fluentd"
        networks:
            - bridge

    fluentd:
        image: sarikajoshi/fluentd-mongodb-plugin
        ports:
            - "24224:24224"
        depends_on:
            - "mongo"
        volumes:
            - ./fluentd/etc:/fluentd/etc
        networks:
            - bridge

    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - ./data/mongodbData:/data/db
            - ./data/configDb:/data/configdb
        networks:
            - bridge

    mongo-express:
        image: mongo-express:latest
#        build: ./mongo-express
        ports:
            - 8081:8081
        depends_on:
            - "mongo"
        networks:
            - bridge

networks:
  bridge:
